GET http://localhost:3003/API/products

###
GET https://inventory-kwv2.onrender.com/api/products

###
GET http://localhost:3003/api/warehouses

###
GET http://localhost:3003/api/suppliers
###
POST http://api/orders/create