GET http://localhost:3004/API/products

###
GET http://localhost:3004/api/products

###
GET http://localhost:3003/api/warehouses

###
GET http://localhost:3003/api/suppliers
###
POST http://api/orders/create